# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GitHubActionForPytest:
  # This workflow contains a single job called "build"
    # The type of runner that the job will run on
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [-f requirement.txt]; then pip install -r requirements.txt; fi
      - name: Tests
        run: python3 setup.py develop && python3 -m pytest
        # uses: cclauss/Github-Action-for-pytest@v2
        # with: 
          # args: python3 setup.py develop && python3 -m pytest
      
          